services:
  web:
    build: ./app
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: